name: Go Build
on:
  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        uses: actions/setup-go@v5
        with:
          go-version: '^1.26.0'
      - run: |
          cd cmd/rdap
          go build -o rdap